name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.19.0
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.0
    - name: Build and Deploy
      uses: di-sagli/WeatherPage
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: docs/
        BUILD_SCRIPT: npm install && npm run build -- --prod
